name = "hanlasan-bbq"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "hanlasan-bbq"

[[d1_databases]]
binding = "DB"
database_name = "hanlasan-bbq"
database_id = "3893e279-deda-493d-8c95-8c087dc3377b"

[[routes]]
pattern = "xn--oi2b40g9l97kpyk0jjr0ee5l.kr"
custom_domain = true

[[routes]]
pattern = "www.xn--oi2b40g9l97kpyk0jjr0ee5l.kr"
custom_domain = true

[[routes]]
pattern = "xn--9g3b2j55zr3f7ud.kr"
custom_domain = true

[[routes]]
pattern = "www.xn--9g3b2j55zr3f7ud.kr"
custom_domain = true

[triggers]
crons = ["0 18 * * *"]

[vars]
SITE_URL = "https://한라산출장바베큐.kr"
NOTIFY_EMAILS = "ohnamsoo3822@naver.com,ohb4199@gmail.com"
SENDER_EMAIL = "한라산출장바베큐 <noreply@xn--oi2b40g9l97kpyk0jjr0ee5l.kr>"
TURNSTILE_SITE_KEY = "0x4AAAAAADWExXMJeUjuUznJ"
